### ISSUE TITLE
More arguments to console app

### ISSUE THREAD

**Issue by ephraimbuddy** [markessien/mlclassification#51]
Currently, typing this on command line:

    python app.py train

Uses the default datasets to train model. I want to add this :

    python app.py train -trp train_path -tep test path

This will enable us to accept training data folder as well as test data folder.

If we type:

    python app.py train

Without specifying any folder, it'll default to using ./datasets/training_set and ./datasets/test_set for training and test data set we provided

For this task, I'll be working on  app.py and utils/train_model.py

**Comment by YourFavouriteOreo** [comment]
As lead of UI I can confirm we need this
